GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST http://158.180.70.60:8080/api/v1/auth/user HTTP/1.1
content-type: application/json

{
    "username": "test@naver.com",
    "password": "testtest1124"
}
